### ISSUE TITLE
flask freeze: Name or service not known

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/pyconfr-2020#4]
J'ai essayé de mettre en prod, mais que ce soit dans github actions ou sur mon laptop j'ai l'exception suivante :

<details>
<summary>
Name or service not known
</summary>

```
$ FLASK_APP=pyconfr.py .venv/bin/flask freeze
/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/flask_frozen/__init__.py:29: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Mapping, namedtuple
[2020-08-02 11:24:33,091] ERROR in app: Exception on /2020/pyconfr-2020.ics [GET]
Traceback (most recent call last):
  File "/home/mdk/.local/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/mdk/.local/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/mdk/.local/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/mdk/.local/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/mdk/.local/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/home/mdk/.local/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/home/mdk/.local/lib/python3.8/http/client.py", line 1402, in connect
    super().connect()
  File "/home/mdk/.local/lib/python3.8/http/client.py", line 917, in connect
    self.sock = self._create_connection(
  File "/home/mdk/.local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/mdk/.local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mdk/clones/afpy/pyconfr-2020/pyconfr.py", line 105, in calendar
    with urlopen('https://cfp-2020.pycon.fr/schedule/ics/') as fd:
  File "/home/mdk/.local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/mdk/.local/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/mdk/.local/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/mdk/.local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/mdk/.local/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/mdk/.local/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
Traceback (most recent call last):
  File ".venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/mdk/clones/afpy/pyconfr-2020/pyconfr.py", line 116, in freeze
    Freezer(app).freeze()
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/flask_frozen/__init__.py", line 199, in freeze
    return set(page.url for page in self.freeze_yield())
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/flask_frozen/__init__.py", line 199, in <genexpr>
    return set(page.url for page in self.freeze_yield())
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/flask_frozen/__init__.py", line 183, in freeze_yield
    new_filename = self._build_one(url)
  File "/home/mdk/clones/afpy/pyconfr-2020/.venv/lib/python3.8/site-packages/flask_frozen/__init__.py", line 321, in _build_one
    raise ValueError('Unexpected status %r on URL %s' \
ValueError: Unexpected status '500 INTERNAL SERVER ERROR' on URL /2020/pyconfr-2020.ics

```
</details>

**Comment by JulienPalard** [comment]
@liZe @annabellou une idée ?

**Comment by gentooboontoo** [comment]
Je pense que c'est dû au fait que https://cfp-2020.pycon.fr/schedule/ics/ n'existe pas encore. @liZe, faut-il désactiver cette partie ?

**Comment by liZe** [comment]
> @liZe, faut-il désactiver cette partie ?

Oui.

**Comment by liZe** [comment]
J’ai corrigé et pushé. Il y a encore des warnings sur des pages qui manquent, c’est normal.

**Comment by gentooboontoo** [comment]
Thanks!
